### PR TITLE
Enable parallel downloads by default.

### PR DESCRIPTION
**Pull request by Edu4rdSHL**
It will speed up the downloading process.

### CODE REVIEW

**Review by JustTNE — COMMENTED** [review]
Basically LGTM, but up for discussion: Is 10 a good number for us here? Packages building in parallel would potentially result in a LOT of concurrent connections to the top mirror.

**Comment by Edu4rdSHL** [comment]
Well, as we use [the mirror from coudflaremirrors.com](https://github.com/chaotic-aur/toolbox/blob/e39dbf07dc2c0587058f4cb6f4fd78ac4161d35e/src/chaotic.sh#L20) we shouldn't have problems, I would be more worried about the Garuda repo itself, imo.

**Review by dr460nf1r3 — APPROVED** [review]

**Comment by dr460nf1r3** [comment]
I also think Cloudflare is able to handle that. As for our repo, it is mostly the local repo or builds.garudalinux.org being used so that should be fine too.

**Review by JustTNE — APPROVED** [review]
LGTM

**Comment by Edu4rdSHL** [comment]
In order to take advantage of it, people would need to re-create the lowerstrap if not using a volatile storage mountpoint.

**Comment by dr460nf1r3** [comment]
Dragon-cluster and garuda-cluster are updated 🧑‍💻

**Pull request merged**
